# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abc458893c52492d10a0f462cf864e2194eaaa443e2353169aea0b695b0125a5954b6cf5c819eab90586c056eb57f59ce72ee77760a98c36f5817ec6b28e9bad

test:
  secret_key_base: e74d7dd47bbc3101c598fba6fe4f5953fda56a41b69a48171915485876acd277ab8a05651baa1dc60c38941bb418e90b85d715b652cc2e8da818b7ba18b5877f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
